### ISSUE TITLE
get_places_yelp.py ConnectionError (after about 1000 requests)

### ISSUE THREAD

**Issue by VictorThibert** [VictorThibert/cpf#13]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.yelp.com', port=443): Max retries exceeded with url: /v3/businesses/search?limit=3&latitude=45.52167939999999&radius=200&term=Dick%27s%2BDeli&longitude=-73.5951511&categories=restaurants (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd242c09748>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by laurenceli** [comment]
unsubscribe

i don't have the mental fortitude to keep up with this

**Comment by VictorThibert** [comment]
Confirmed. Thank you for Subscribing to  requests.exceptions.ConnectionError: HTTPSConnectionPool Facts! Did you know that  requests.exceptions.ConnectionError: HTTPSConnectionPool occurs whenever it sees fit? There is not logical reasoning as to why or why it happens. Haha!
